export const DEMO_TRUCKS = [
  {
    id: "TRK-2051",
    plate: "鲁 Q·7K218",
    carrier: "达丰物流",
    driver: "张师傅",
    destination: "达丰苏州配送中心",
    shipment: "SHP-78442",
    dock: 0,
    offset: 0,
    color: "#2855ce",
    direction: "outbound" as const,
    sku: 0,
    units: 24,
  },
  {
    id: "TRK-2287",
    plate: "鲁 Q·6J092",
    carrier: "达丰供应链",
    driver: "李师傅",
    destination: "达丰杭州配送中心",
    shipment: "SHP-78447",
    dock: 1,
    offset: 72,
    color: "#e58440",
    direction: "inbound" as const,
    sku: 1,
    units: 12,
  },
  {
    id: "TRK-2136",
    plate: "鲁 Q·3N165",
    carrier: "达丰冷链",
    driver: "陈师傅",
    destination: "达丰南京配送中心",
    shipment: "SHP-78451",
    dock: 2,
    offset: 161,
    color: "#489792",
    direction: "outbound" as const,
    sku: 2,
    units: 18,
  },
];
